### ISSUE TITLE
App Not run

### ISSUE THREAD

**Issue by shamshadpattani** [SanketSarmalkar/Stree_Kavach#2]
its stuck on First  screen only show  icon in a blank white page ? no error shown

**Comment by shamshadpattani** [comment]
Also show .env file is missing  in asset  ? what is in side .env file

**Comment by SanketSarmalkar** [comment]
Its working fine, I won't provide .env file but will soon release the apk
file of the same.

**Comment by SanketSarmalkar** [comment]
@shamshadpattani, to get the app download it from this link attached below.
[https://drive.google.com/file/d/1KtOBLCkjVhdeGePe4b5Drfj-k5uzvtKg/view?usp=drive_link](url)
